# This is a working example.
# For a more complete reference use `--example`
kibot:
  version: 1

global:
  filters:
  - number: 1007
  - number: 1015
  - number: 58

filters:
- name: only_jlc_parts
  comment: Only parts with JLC (LCSC) code
  type: generic
  include_only:
  - column: LCSC#
    regex: ^C\d+

variants:
- name: place_holder
  comment: Just a place holder for pre_transform filters
  type: kicost
  pre_transform:
  - _kicost_rename
  - _rot_footprint

outputs:
# - name: gerber_modern
#   comment: Gerbers in modern format, recommended by the standard
#   type: gerber
#   dir: Gerbers_and_Drill
#   layers:
#   - layer: F.Cu
#     suffix: F_Cu
#     description: Front copper
#   - layer: B.Cu
#     suffix: B_Cu
#     description: Bottom copper
#   - layer: B.Paste
#     suffix: B_Paste
#     description: Bottom solder paste
#   - layer: B.Silkscreen
#     suffix: B_Silkscreen
#     description: Bottom silkscreen (artwork)
#   - layer: F.Silkscreen
#     suffix: F_Silkscreen
#     description: Front silkscreen (artwork)
#   - layer: B.Mask
#     suffix: B_Mask
#     description: Bottom soldermask (negative)
#   - layer: F.Mask
#     suffix: F_Mask
#     description: Front soldermask (negative)
#   - layer: User.Drawings
#     suffix: User_Drawings
#     description: User drawings
#   - layer: User.Comments
#     suffix: User_Comments
#     description: User comments
#   - layer: Edge.Cuts
#     suffix: Edge_Cuts
#     description: Board shape
#   - layer: B.Courtyard
#     suffix: B_Courtyard
#     description: Bottom courtyard area
#   - layer: F.Courtyard
#     suffix: F_Courtyard
#     description: Front courtyard area
#   - layer: B.Fab
#     suffix: B_Fab
#     description: Bottom documentation
#   - layer: F.Fab
#     suffix: F_Fab
#     description: Front documentation

- name: JLCPCB_gerbers
  comment: Gerbers compatible with JLCPCB
  type: gerber
  dir: JLCPCB_front
  options:
    exclude_edge_layer: true
    exclude_pads_from_silkscreen: true
    plot_sheet_reference: false
    plot_footprint_refs: true
    plot_footprint_values: false
    force_plot_invisible_refs_vals: false
    tent_vias: true
    use_protel_extensions: true
    create_gerber_job_file: false
    disable_aperture_macros: true
    gerber_precision: 4.6
    use_gerber_x2_attributes: false
    use_gerber_net_attributes: false
    line_width: 0.1
    subtract_mask_from_silk: true
    inner_extension_pattern: .gp%n
  layers: &id002
  - layer: F.Cu
    suffix: F_Cu
    description: Front copper
  - layer: B.Cu
    suffix: B_Cu
    description: Bottom copper
  - layer: B.Paste
    suffix: B_Paste
    description: Bottom solder paste
  - layer: B.Silkscreen
    suffix: B_Silkscreen
    description: Bottom silkscreen (artwork)
  - layer: F.Silkscreen
    suffix: F_Silkscreen
    description: Front silkscreen (artwork)
  - layer: B.Mask
    suffix: B_Mask
    description: Bottom soldermask (negative)
  - layer: F.Mask
    suffix: F_Mask
    description: Front soldermask (negative)
  - layer: Edge.Cuts
    suffix: Edge_Cuts
    description: Board shape
- name: JLCPCB_drill
  comment: Drill files compatible with JLCPCB
  type: excellon
  dir: JLCPCB_front
  options:
    pth_and_npth_single_file: false
    pth_id: -PTH
    npth_id: -NPTH
    metric_units: true
    map: gerber
    route_mode_for_oval_holes: false
    output: '%f%i.%x'
- name: Gerber_front
  comment: ZIP file for JLCPCB
  type: compress
  #dir: /
  options:
    files:
    - from_output: JLCPCB_gerbers
      dest: /
    - from_output: JLCPCB_drill
      dest: /