# This is a working example.
# For a more complete reference use `--example`
kibot:
  version: 1

outputs:

- name: generic_bom_xlsx
  comment: Generic Bill of Materials in XLSX format
  type: bom
  dir: bom
  options:
    format: XLSX
    columns:
    - Row
    - Description
    - References
    - Value
    - Footprint
    - Quantity Per PCB
    - Comment
    group_fields:
      - Value
      - Footprint
    count_smd_tht: true
    xlsx: 
      logo: false

- name: basic_ibom
  comment: Interactive HTML BoM
  type: ibom
  dir: bom
  output_id: -global

- name: basic_pcbdraw_png_set_black_hasl_top
  comment: PCB 2D render in PNG format, using set-black-hasl style
  type: pcbdraw
  dir: image
  options:
    style: set-black-hasl
    format: png
 
- name: basic_pdf_sch_print
  comment: Schematic in PDF format
  type: pdf_sch_print
  dir: image
- name: basic_svg_sch_print
  comment: Schematic in SVG format
  type: svg_sch_print
  dir: image

- name: basic_render_3d_top
  comment: 3D view from top
  type: render_3d
  dir: image
  options:
    ray_tracing: true
    orthographic: true
    zoom: 3
- name: basic_render_3d_30deg
  comment: 3D view from 30 degrees
  type: render_3d
  dir: image
  output_id: 30deg
  options:
    ray_tracing: true
    rotate_x: 3
    rotate_z: -2
    zoom: 3
- name: basic_render_3d_bottom
  comment: 3D view from bottom
  type: render_3d
  dir: image
  options:
    ray_tracing: true
    orthographic: true
    view: bottom
    zoom: 3
